name: bkdev
channels:
  - conda-forge
dependencies:
  - python>=3.7

  # build
  - setuptools
  - nodejs>=14
  - yaml

  # runtime
  - jinja2>=2.7
  - numpy>=1.11.3
  - packaging>=16.8
  - pillow>=4.0
  - python-dateutil>=2.1
  - pyyaml>=3.10
  - tornado>=5
  - typing_extensions>=3.7.4

  # docs
  - colorcet
  - pygments
  - sphinx >=1.8
  - sphinx-panels
  - pip
  - pip:
    - sphinxext-opengraph
    - sphinx-reredirects

  # tests
  - beautifulsoup4
  - black
  - channels
  - click
  - colorama
  - coverage
  - firefox
  - flake8
  - flaky
  - geckodriver
  - ipython
  - isort <5.0
  - mock
  - mypy <=0.782
  - nbconvert >=5.4
  - networkx
  - nodejs >=14
  - numba
  - pandas
  - psutil
  - pydot
  - pytest 6.0*
  - pytest-asyncio >=0.12.0
  - pytest-cov >=1.8.1
  - pytest-html
  - pytest-xdist
  - requests >=1.2.3
  - selenium >=3.8
  - scipy

  # examples
  - flask >=1.0
  - django
  - h5py
  - icalendar
  - networkx
  - notebook
  - opencv
  - pyshp
  - scikit-learn
  - sympy
  #- ipywidgets_bokeh >=1.0.0
  #- ipywidgets >=7.5.0
  #- ipyvolume
  #- ipyleaflet
