name: 'Test Setup'

description: 'Perform Setup Steps for Bokeh CI Test Jobs'

inputs:
  test-env:
    # string: "environment-test-{{ test-env }}.yml"
    description: 'Test environment file to use'
    required: true
  source-tree:
    # string: "keep" or "delete"
    # (avoiding booleans: https://github.com/actions/runner/issues/1483)
    description: 'Whether to keep or delete the source tree'
    required: true
  sampledata:
    # string: "download", "cached", or "none"
    description: 'How or if to install sampledata'
    required: true

runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'
        activate-environment: bk-test
        run-post: ${{ runner.os != 'Windows' }}

    - name: Install libmamba solver
      shell: bash -l {0}
      run: |
        conda install -q -n base conda-libmamba-solver
        conda config --set solver libmamba

    - name: Update bk-test environment
      shell: bash -l {0}
      run: |
        conda env update -q -n bk-test -f conda/environment-test-${{ inputs.test-env }}.yml

    - name: Download wheel package
      id: download
      uses: actions/download-artifact@v3
      with:
        name: wheel-package
        path: dist/

    - name: Install wheel package
      shell: bash -l {0}
      run: pip install dist/bokeh-*-py3-none-any.whl

    - name: Download bokehjs package
      uses: actions/download-artifact@v3
      with:
        name: bokehjs-package
        path: bokehjs/build/dist/

    - name: Symlink bokehjs package
      shell: bash -l {0}
      working-directory: ./bokehjs/build/dist/
      run: ln -s $(ls -t bokeh-bokehjs-*.tgz | head -n 1) bokeh-bokehjs.tgz

    - name: Cache node modules
      if: ${{ inputs.source-tree == 'keep' }}
      uses: actions/cache@v3
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-node-${{ hashFiles('bokehjs/package-lock.json') }}

    - name: Install node modules
      if: ${{ inputs.source-tree == 'keep' }}
      shell: bash -l {0}
      run: bash scripts/ci/install_node_modules.sh

    - name: Cache sampledata
      if: ${{ inputs.sampledata == 'cache' }}
      uses: actions/cache@v3
      with:
        path: ~/.bokeh/data
        key: ${{ runner.os }}-sampledata-${{ hashFiles('bokeh/util/sampledata.json') }}

    - name: Install sampledata
      if: ${{ inputs.sampledata != 'none' }}
      shell: bash -l {0}
      run: python -c 'import bokeh; bokeh.sampledata.download(progress=False)'

    - name: Delete repository source tree
      if: ${{ inputs.source-tree == 'delete' }}
      shell: bash -l {0}
      run: rm -rf src/bokeh
