name: bk-test
channels:
  - conda-forge
dependencies:
  - python=3.9

  # runtime
  - contourpy >=1.2
  - jinja2 >=2.7
  - numpy >=1.16
  - packaging >=16.8
  - pillow >=4.0
  - python-dateutil >=2.1
  - pyyaml >=3.10
  - tornado >=5
  - xyzservices>=2021.09.1

  # tests
  - pytest >=7.0
  - pytest-timeout
  - scipy
