name: bk-test
channels:
  - conda-forge
dependencies:
  - python=3.9

  # runtime
  - contourpy >=1
  - jinja2 >=2.7
  - numpy >=1.16
  - packaging >=16.8
  - pandas 1.2
  - pillow >=4.0
  - python-dateutil >=2.1
  - pyyaml >=3.10
  - tornado 5.1.*
  - xyzservices>=2021.09.1

  # tests
  - beautifulsoup4
  - channels
  - click
  - colorama
  - colorcet
  - coverage
  - firefox =>96
  - geckodriver
  - ipython
  - isort 5.8
  - json5
  - nbconvert >=5.4
  - nodejs 18.*
  - pre-commit
  - psutil
  - pygments
  - pygraphviz
  - pytest >=7.0
  - pytest-asyncio=0.12.0
  - pytest-cov >=1.8.1
  - pytest-html
  - pytest-xdist
  - pytest-timeout
  - requests >=1.2.3
  - selenium 4.2

  # examples
  - h5py
  - icalendar
  - pandas-datareader
  - pyshp

  # pip dependencies
  - pip
  - pip:
    - mypy >=0.990
    # docs
    - autoclasstoc <=1.4
    - pydata_sphinx_theme ==0.9
    - requests-unixsocket >= 0.3.0
    - sphinx ==5.3
    - sphinx-copybutton
    - sphinx-design
    - sphinxext-opengraph
    # tests
    - ruff ==0.0.252
    - types-boto
    - types-colorama
    - types-mock
    - types-pillow
    - types-pyyaml
    - types-requests
