name: bk-release-build
channels:
  - conda-forge
dependencies:
  - python=3.8

  # runtime
  - jinja2 >=2.7
  - numpy >=1.11.3
  - packaging >=16.8
  - pillow >=4.0
  - python-dateutil >=2.1
  - pyyaml >=3.10
  - tornado >=5
  - typing_extensions >=3.10.0
  - xyzservices>=2021.09.1

  # build
  - boto
  - colorama
  - conda-build=3.21.7
  - conda-verify=3.4.2
  - libiconv
  - nodejs 16.*
  - ripgrep=0.10.0
  - setuptools
  - yaml

  # docs
  - colorcet
  - firefox =>96
  - geckodriver
  - icalendar
  - ipython
  - networkx
  - pandas
  - pydot
  - pygments
  - pyshp
  - scipy

  # pip dependencies
  - pip
  - pip:
    # docs
    - autoclasstoc
    - pydata_sphinx_theme >=0.7.1
    - sphinx >=4.3.2
    - sphinx-copybutton
    - sphinxext-opengraph
    - sphinx-panels
    - sphinx-tabs
    - sphinx-reredirects
