name: bk-test
channels:
  - conda-forge
dependencies:
  - python=3.7

  # runtime
  - jinja2 >=2.7
  - numpy >=1.11.3
  - packaging >=16.8
  - pillow >=4.0
  - python-dateutil >=2.1
  - pyyaml >=3.10
  - tornado >=5
  - typing_extensions >=3.7.4

  # build
  - boto
  - colorama
  - conda-build=3.18.10
  - conda-verify=3.4.2
  - nodejs>=10.13
  - packaging
  - ripgrep=0.10.0
  - setuptools
  - yaml

  # docs
  - colorcet
  - firefox
  - geckodriver
  - networkx
  - numpy
  - pandas
  - pydot
  - pygments
  - scipy
  - sphinx
  - pip
  - pip:
    - sphinx-panels
