name: bk-release-build
channels:
  - conda-forge
dependencies:
  - python=3.7

  # runtime
  - jinja2 >=2.7
  - numpy >=1.11.3
  - packaging >=16.8
  - pillow >=4.0
  - python-dateutil >=2.1
  - pyyaml >=3.10
  - tornado >=5
  - typing_extensions >=3.10.0

  # build
  - boto
  - colorama
  - conda-build=3.20.5
  - conda-verify=3.4.2
  - libiconv
  - nodejs 14.*
  - ripgrep=0.10.0
  - setuptools
  - yaml

  # docs
  - colorcet
  - firefox
  - geckodriver
  - icalendar
  - networkx
  - pandas
  - pydot
  - pygments
  - scipy
  - sphinx >=3.5
  - sphinx-panels
  - pip
  - pip:
    - autoclasstoc
    - pydata_sphinx_theme
    - sphinxext-opengraph
    - sphinx-reredirects
