name: bk-test
channels:
  - conda-forge
dependencies:
  - python=3.10

  # runtime
  - jinja2 >=2.7
  - numpy >=1.11.3
  - packaging >=16.8
  - pillow >=4.0
  - python-dateutil >=2.1
  - pyyaml >=3.10
  - tornado >=5
  - typing_extensions >=3.10.0
  - xyzservices>=2021.09.1

  # tests
  - beautifulsoup4
  - channels
  - click
  - colorama
  - colorcet
  - coverage
  - firefox
  - flake8
  - flaky
  - geckodriver
  - ipython
  - isort 5.8
  - mock
  - mypy >=0.910
  - pandas-stubs
  - nbconvert >=5.4
  - networkx
  - nodejs 14.*
  #- numba
  - pandas
  - psutil
  - pydot
  - pygments
  - pytest 6.2*
  - pytest-asyncio
  - pytest-cov >=1.8.1
  - pytest-html
  - pytest-xdist
  - requests >=1.2.3
  - selenium >=3.8
  - scipy
  - pre-commit

  # examples
  - flask >=1.0
  - django
  - h5py
  - icalendar
  - networkx
  - notebook
  - opencv
  - pyshp
  - scikit-learn
  - sympy

  # pip dependencies
  - pip
  - pip:
    # docs
    - autoclasstoc
    - pydata_sphinx_theme >=0.7.1
    - sphinx >=4.1,<4.3
    - sphinxext-opengraph
    - sphinx-panels
    - sphinx-tabs
    - sphinx-reredirects
    # tests
    - types-boto
    - types-colorama
    - types-mock
    - types-pillow
    - types-pyyaml
    - types-requests
    - flake8-pyi
